default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: pretty-format-json
      - id: check-merge-conflict # Check for merge conflict markers
      - id: check-toml # Validate TOML files
      - id: check-xml # Validate XML files
      - id: mixed-line-ending # Ensure consistent line endings
      - id: check-case-conflict # Check for case conflicts
      - id: fix-byte-order-marker # Remove UTF-8 byte order marker

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: ["--fix", "--config=./fastapi-base/pyproject.toml"]
      - id: ruff-format
        args: ["--config=./fastapi-base/pyproject.toml"]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--settings-path=./fastapi-base/pyproject.toml"]

  # JSON/YAML validation and formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [css, javascript, ts, tsx, json, markdown, yaml]

  # Dockerfile linting
  # needs to be fixed to work on CI
  #   - repo: https://github.com/hadolint/hadolint
  #     rev: v2.12.0
  #     hooks:
  #       - id: hadolint
  #         files: ^.*Dockerfile.*$

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # Git commit message linting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # SQL formatting
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix
