volumes:
  base-data:
  db-data:
  redis-data:
services:
  fastapi-base:
    restart: always
    env_file:
      - .env
    build:
      context: ./fastapi-base
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
    ports:
      - "8666:8000"
    command: |
      bash -c "
      gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60 --reload"
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - base-data:/data
      - ./fastapi-base/src:/code/src
      - ./fastapi-base/tests:/code/tests
      - ./fastapi-base/alembic.ini:/code/alembic.ini
      - ./fastapi-base/logconfig.yml:/code/logconfig.yml
 
