services:
  fastapi-base:
    build:
      context: ../fastapi-base
      dockerfile: ./Dockerfile
      args:
        env: "test"
    command: |
        bash -c "
        while !</dev/tcp/db-test/5432; do sleep 1; done;
        gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60"
    environment:
      - PYTHONUNBUFFERED=0
      - PROJECT_NAME=test
      - VERSION=v1
      - DEVELOPER=test
      - ENV=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db-test
    volumes:
      - /data:/data  # to access coverage.xml
    depends_on:
      - db-test
  db-test:
    image: postgres:18rc1-alpine3.22
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db-test
