name: unit-tests
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          docker compose -f ops/docker-compose.test.yml up --detach --wait
          docker compose -f ops/docker-compose.test.yml exec ciex-backend pytest --cov-report=xml:/data/coverage.xml --cov=src/ tests/
      - name: Copy coverage file from container
        run: |
          docker compose -f ops/docker-compose.test.yml cp ciex-backend:/data/coverage.xml ./coverage.xml
      - name: Codecov
        if: success()
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Clean-up
        if: always()
        run: |
          docker compose -f ops/docker-compose.test.yml down -v
